### PR TITLE
Bug/sitedefinition id no match

### LINKED ISSUE #9: No match on siteDefinition Id anymore
SiteDefinistionSyncronizer does not check if Id is provided. If so it should search with the ID and not the name.

### PR DESCRIPTION
**Pull request by ovelartelius**
Fix so that it try to match Id before match on sitedefinition name

### CODE REVIEW

File: Addon.Episerver.EnvironmentSynchronizer/Configuration/SiteDefinitionElement.cs [hunk 1]
```diff
@@ -33,5 +33,11 @@ public HostCollection Hosts
 	        get => (HostCollection)base["hosts"];
         }
 
+        [ConfigurationProperty("Force", IsRequired = false)]
+        public bool Force
```
Comment (LinusEkstrom) [inline Addon.Episerver.EnvironmentSynchronizer/Configuration/SiteDefinitionElement.cs:37]: What's the purpose of this configuration attribute? I can't see it being used in the code.

**Review by LinusEkstrom — CHANGES_REQUESTED** [review]

File: Addon.Episerver.EnvironmentSynchronizer/Configuration/SiteDefinitionElement.cs (hunk 1 above)
Comment (ovelartelius) [reply Addon.Episerver.EnvironmentSynchronizer/Configuration/SiteDefinitionElement.cs]: I forgot to remove it. But an update is sent in with removal of Force settings.
